export const STORE_FETCHED_PRODUCTS_AND_IMAGES_JSON_DATA = 'STORE_FETCHED_PRODUCTS_AND_IMAGES_JSON_DATA';
export const HEIGHT_OF_THREE_ELEMENT_TAB_BAR = 'HEIGHT_OF_THREE_ELEMENT_TAB_BAR';
export const STORE_CATEGORY = 'STORE_CATEGORY';
export const STORE_SELECTED_BRAND_YEAR_MODEL = 'STORE_SELECTED_BRAND_YEAR_MODEL';